name: Build and Push Image

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 5"

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: baneofserenity/sabnzbd-ffmpeg
        tags: latest ${{ github.sha }}

    # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
    # in which case 'username' and 'password' can be omitted.
    - name: Push To dockerhub
      id: push-to-dockerhub
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: registry.hub.docker.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-dockerhub.outputs.registry-paths }}"