name: Docker Image CI Unstable

on:
  push:
    branches: [ unstable ]
  schedule:
    - cron: "0 0 * * 5"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag baneofserenity/sabnzbd-ffmpeg:unstable-$(date +%s) --tag baneofserenity/sabnzbd-ffmpeg:unstable
